# Generated by Django 6.0.6 on 2026-07-04 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_tag_task_description_remove_task_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='color',
            field=models.CharField(default='#6B7280', max_length=7),
        ),
    ]
